# Fix autogenerated file after build
$file = "android\app\build\generated\autolinking\src\main\java\com\facebook\react\ReactNativeApplicationEntryPoint.java"

if (Test-Path $file) {
    Write-Host "Fixing autogenerated file..."
    $content = Get-Content $file -Raw
    $content = $content -replace 'com\.farmaa', 'com.furmaa'
    Set-Content $file -Value $content -NoNewline
    Write-Host "✅ File fixed! Package name updated to com.furmaa"
} else {
    Write-Host "⚠️ File not found. Build first, then run this script."
}








